version: '3'

services:

  db:
    image: mongo
    ports:
      - "27017:27017"

  service:
    build: .
    command: /bin/app
    environment:
      - ACCESS_TOKEN=my-super-secret
      - MONGO_URI=mongodb://db:27017
    ports:
      - "9999:9999"
